# Generated by Django 5.1.4 on 2025-03-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0016_examplemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='people',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='games',
            field=models.BooleanField(null=True, verbose_name='ゲーム・漫画セット'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='men',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='男性人数'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='others',
            field=models.BooleanField(null=True, verbose_name='その他'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='women',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='女性人数'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='yakiniku',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='焼肉セット数量'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
