# Generated by Django 5.1.4 on 2025-03-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0017_remove_examplemodel_people_remove_examplemodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='messages',
            field=models.TextField(blank=True, null=True, verbose_name='要望'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='check_in_date',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='チェックイン日'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='check_out_date',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='チェックアウト日'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='furigana',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ふりがな'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号'),
        ),
    ]
