# Generated by Django 5.1.4 on 2025-03-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0018_examplemodel_messages_alter_examplemodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='soumen',
            field=models.BooleanField(null=True, verbose_name='流しそうめん'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='men',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='男性'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='women',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='女性'),
        ),
    ]
