# Generated by Django 5.1.4 on 2025-03-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0019_examplemodel_soumen_alter_examplemodel_men_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='games',
            field=models.BooleanField(default='', verbose_name='ゲーム・漫画セット'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='others',
            field=models.BooleanField(default='', verbose_name='その他'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='soumen',
            field=models.BooleanField(default='', verbose_name='流しそうめん'),
        ),
    ]
