# Generated by Django 5.1.4 on 2025-03-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0025_alter_examplemodel_games_alter_examplemodel_others_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='games',
            field=models.BooleanField(blank=True, null=True, verbose_name='ゲーム・漫画セット'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='others',
            field=models.BooleanField(blank=True, null=True, verbose_name='その他'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='soumen',
            field=models.BooleanField(blank=True, null=True, verbose_name='流しそうめん'),
        ),
    ]
