# Generated by Django 5.1.4 on 2025-03-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0026_alter_examplemodel_games_alter_examplemodel_others_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='soumen',
        ),
    ]
