# Generated by Django 5.1.4 on 2025-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0027_remove_examplemodel_soumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='games',
            field=models.BooleanField(null=True, verbose_name='ゲーム・漫画セット'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='others',
            field=models.BooleanField(null=True, verbose_name='その他'),
        ),
    ]
