# Generated by Django 5.1.4 on 2025-03-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0031_alter_examplemodel_games_alter_examplemodel_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='soumen',
            field=models.BooleanField(blank=True, default=False, verbose_name='流しそうめん'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='games',
            field=models.BooleanField(blank=True, default=False, verbose_name='ゲーム・漫画セット'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='others',
            field=models.BooleanField(blank=True, default=False, verbose_name='その他'),
        ),
    ]
