# Generated by Django 5.1.4 on 2025-05-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0032_examplemodel_soumen_alter_examplemodel_games_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='games',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='others',
        ),
    ]
