# Generated by Django 5.1.4 on 2025-06-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0033_remove_examplemodel_games_remove_examplemodel_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='maki',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='薪の数量'),
        ),
    ]
